ELPP-3163 Various upgrades for 0.2
elifesciences/proofreader-php pull request #7
Opened 2018-03-08 14:46 UTC by giorgiosironi

2018-03-08 15:44 UTC, giorgiosironi commented
This is the changes made to journal by running the new `php-cs-fixer` appropriately configured:
```
diff --git a/src/Controller/LabsController.php b/src/Controller/LabsController.php
index a5c7eb9..f1f263d 100644
--- a/src/Controller/LabsController.php
+++ b/src/Controller/LabsController.php
@@ -67,7 +67,6 @@ final class LabsController extends Controller
             'Exploring open-source solutions at the intersection of research and technology.
             <a href="https://elifesciences.org/events/c40798c3/elife-innovation-sprint-2018?utm_source=Labs-home&utm_medium=website&utm_campaign=Sprint-apply">Join us</a> to prototype ideas to bring cutting-edge technology to open research this May.'
 // ON MARCH 5, REVERT LINE ABOVE BACK TO: Learn more about <a href="'.$this->get('router')->generate('about-innovation').'">innovation at eLife</a>, follow us on <a href="https://twitter.com/eLifeInnovation">Twitter</a>, or sign up for our <a href="https://crm.elifesciences.org/crm/tech-news?utm_source=Labs-home&utm_medium=website&utm_campaign=technews">technology and innovation newsletter</a>.'
-
         );
 
         return new Response($this->get('templating')->render('::labs.html.twig', $arguments));
diff --git a/src/Helper/CanConvert.php b/src/Helper/CanConvert.php
index cc401d2..88eb2ad 100644
--- a/src/Helper/CanConvert.php
+++ b/src/Helper/CanConvert.php
@@ -8,14 +8,14 @@ trait CanConvert
 {
     use HasViewModelConverter;
 
-    final protected function willConvertTo(string $viewModel = null, array $context = []): callable
+    final protected function willConvertTo(string $viewModel = null, array $context = []) : callable
     {
         return function ($object) use ($viewModel, $context) {
             return $this->convertTo($object, $viewModel, $context);
         };
     }
 
-    final protected function convertTo($object, string $viewModel = null, array $context = []): ViewModel
+    final protected function convertTo($object, string $viewModel = null, array $context = []) : ViewModel
     {
         return $this->getViewModelConverter()->convert($object, $viewModel, $context);
     }
diff --git a/src/Helper/HasPages.php b/src/Helper/HasPages.php
index 6d517b1..abbd6e5 100644
--- a/src/Helper/HasPages.php
+++ b/src/Helper/HasPages.php
@@ -22,7 +22,7 @@ trait HasPages
             });
     }
 
-    final private function paginator(PromiseInterface $pagerfantaPromise, Request $request, string $title, string $route): PromiseInterface
+    final private function paginator(PromiseInterface $pagerfantaPromise, Request $request, string $title, string $route) : PromiseInterface
     {
         return $pagerfantaPromise
             ->then(function (Pagerfanta $pagerfanta) use ($request, $title, $route) {
diff --git a/src/ViewModel/Converter/Block/CreatesCaptionedAsset.php b/src/ViewModel/Converter/Block/CreatesCaptionedAsset.php
index 6cca60f..18361c7 100644
--- a/src/ViewModel/Converter/Block/CreatesCaptionedAsset.php
+++ b/src/ViewModel/Converter/Block/CreatesCaptionedAsset.php
@@ -15,7 +15,7 @@ trait CreatesCaptionedAsset
     use HasPatternRenderer;
     use HasViewModelConverter;
 
-    final private function createCaptionedAsset(ViewModel\IsCaptioned $viewModel, HasCaption $asset, ViewModel\Doi $doi = null): ViewModel\CaptionedAsset
+    final private function createCaptionedAsset(ViewModel\IsCaptioned $viewModel, HasCaption $asset, ViewModel\Doi $doi = null) : ViewModel\CaptionedAsset
     {
         $caption = $asset->getCaption()->map(function (Block $block) {
             return $this->getViewModelConverter()->convert($block);
diff --git a/src/ViewModel/Converter/FormViewConverter.php b/src/ViewModel/Converter/FormViewConverter.php
index 1903e8a..d87a1a0 100644
--- a/src/ViewModel/Converter/FormViewConverter.php
+++ b/src/ViewModel/Converter/FormViewConverter.php
@@ -6,7 +6,6 @@ use eLife\Journal\Helper\Callback;
 use eLife\Journal\Helper\Humanizer;
 use eLife\Journal\ViewModel\Form;
 use eLife\Journal\ViewModel\HiddenInput;
-use eLife\Journal\ViewModel\HoneypotField;
 use eLife\Patterns\PatternRenderer;
 use eLife\Patterns\ViewModel;
 use eLife\Patterns\ViewModel\MessageGroup;
diff --git a/test/ViewModel/Converter/ModelConverterTestCase.php b/test/ViewModel/Converter/ModelConverterTestCase.php
index 4e55fd9..dd35046 100644
--- a/test/ViewModel/Converter/ModelConverterTestCase.php
+++ b/test/ViewModel/Converter/ModelConverterTestCase.php
@@ -86,7 +86,7 @@ abstract class ModelConverterTestCase extends TestCase
         }
     }
 
-    final private function findSamples() : Traversable
+    private function findSamples() : Traversable
     {
         $this->assertInternalType('array', $this->models);
         $this->assertInternalType('array', $this->viewModelClasses);
```

2018-03-08 15:47 UTC, giorgiosironi commented
This is patterns-php, minor whitespace changes and Yoda conditions:
```
diff --git a/src/Twig/PatternExtension.php b/src/Twig/PatternExtension.php
index fd562ff..590ab8e 100644
--- a/src/Twig/PatternExtension.php
+++ b/src/Twig/PatternExtension.php
@@ -27,7 +27,7 @@ final class PatternExtension extends Twig_Extension
         ];
     }
 
-    public function renderPattern(ViewModel $viewModel): string
+    public function renderPattern(ViewModel $viewModel) : string
     {
         return $this->renderer->render($viewModel);
     }
diff --git a/src/ViewModel/AnnotationTeaser.php b/src/ViewModel/AnnotationTeaser.php
index a0e766e..9f0a5f6 100644
--- a/src/ViewModel/AnnotationTeaser.php
+++ b/src/ViewModel/AnnotationTeaser.php
@@ -78,7 +78,6 @@ final class AnnotationTeaser implements ViewModel
         string $inContextUri,
         string $highlight,
         bool $isRestricted = false
-
     ) : AnnotationTeaser {
         return new static(
             $document,
diff --git a/src/ViewModel/ArticleSection.php b/src/ViewModel/ArticleSection.php
index 88c1a97..31e03d3 100644
--- a/src/ViewModel/ArticleSection.php
+++ b/src/ViewModel/ArticleSection.php
@@ -44,7 +44,7 @@ final class ArticleSection implements ViewModel
             throw new InvalidArgumentException('DOI requires an ID');
         }
 
-        if ($doi !== null) {
+        if (null !== $doi) {
             $doi = FlexibleViewModel::fromViewModel($doi);
             $doi = $doi->withProperty('variant', Doi::ARTICLE_SECTION);
         }
diff --git a/src/ViewModel/AudioPlayer.php b/src/ViewModel/AudioPlayer.php
index f87cda7..000d8aa 100644
--- a/src/ViewModel/AudioPlayer.php
+++ b/src/ViewModel/AudioPlayer.php
@@ -29,7 +29,7 @@ final class AudioPlayer implements ViewModel
         Assertion::notEmpty($chapters);
         Assertion::allIsInstanceOf($chapters, MediaChapterListingItem::class);
         Assertion::allTrue(array_map(function (MediaSource $mediaSource) {
-            return strpos($mediaSource['mediaType']['forMachine'], 'audio') === 0;
+            return 0 === strpos($mediaSource['mediaType']['forMachine'], 'audio');
         }, $sources), 'All sources must be audio types.');
 
         $this->episodeNumber = $episodeNumber;
diff --git a/src/ViewModel/Button.php b/src/ViewModel/Button.php
index 7fd8fda..329de06 100644
--- a/src/ViewModel/Button.php
+++ b/src/ViewModel/Button.php
@@ -41,13 +41,13 @@ final class Button implements ViewModel
         Assertion::notBlank($text);
         Assertion::choice($size, [self::SIZE_CUSTOM, self::SIZE_MEDIUM, self::SIZE_SMALL, self::SIZE_EXTRA_SMALL]);
         Assertion::choice($style, [self::STYLE_DEFAULT, self::STYLE_LOGIN, self::STYLE_OUTLINE, self::STYLE_SPEECH_BUBBLE]);
-        if ($style === self::STYLE_LOGIN) {
-            Assertion::true($size === self::SIZE_EXTRA_SMALL);
+        if (self::STYLE_LOGIN === $style) {
+            Assertion::true(self::SIZE_EXTRA_SMALL === $size);
         }
 
         $classes = [];
 
-        if (self::SIZE_MEDIUM !== $size && $style !== self::STYLE_LOGIN && $size !== self::SIZE_CUSTOM) {
+        if (self::SIZE_MEDIUM !== $size && self::STYLE_LOGIN !== $style && self::SIZE_CUSTOM !== $size) {
             $classes[] = 'button--'.$size;
         }
 
diff --git a/src/ViewModel/CaptionedAsset.php b/src/ViewModel/CaptionedAsset.php
index a4e8b23..ce45c9c 100644
--- a/src/ViewModel/CaptionedAsset.php
+++ b/src/ViewModel/CaptionedAsset.php
@@ -31,7 +31,7 @@ final class CaptionedAsset implements ViewModel
     ) {
         $this->captionText = $captionText;
         $this->setFigure($figure);
-        if ($doi !== null) {
+        if (null !== $doi) {
             $doi = FlexibleViewModel::fromViewModel($doi);
             $this->doi = $doi->withProperty('variant', Doi::ASSET);
         }
diff --git a/src/ViewModel/CompactForm.php b/src/ViewModel/CompactForm.php
index 3c62d35..f4d1e5a 100644
--- a/src/ViewModel/CompactForm.php
+++ b/src/ViewModel/CompactForm.php
@@ -38,7 +38,7 @@ final class CompactForm implements ViewModel
         Assertion::notBlank($ctaText);
         Assertion::allIsInstanceOf($hiddenFields, HiddenField::class);
 
-        if ($state === self::STATE_INVALID) {
+        if (self::STATE_INVALID === $state) {
             Assertion::notNull($messageGroup);
             Assertion::notBlank($messageGroup['errorText']);
         }
diff --git a/src/ViewModel/ListingReadMore.php b/src/ViewModel/ListingReadMore.php
index e9592bb..2112865 100644
--- a/src/ViewModel/ListingReadMore.php
+++ b/src/ViewModel/ListingReadMore.php
@@ -40,19 +40,19 @@ final class ListingReadMore implements ViewModel
         $this->id = $id;
     }
 
-    protected function getComposedViewModels(): Traversable
+    protected function getComposedViewModels() : Traversable
     {
         yield from $this->items;
         yield $this->pagination;
         yield $this->heading;
     }
 
-    public function getTemplateName(): string
+    public function getTemplateName() : string
     {
         return 'resources/templates/listing-read-more.mustache';
     }
 
-    public function getLocalStyleSheets(): Traversable
+    public function getLocalStyleSheets() : Traversable
     {
         yield 'resources/assets/css/listing.css';
     }
diff --git a/src/ViewModel/ReadMoreItem.php b/src/ViewModel/ReadMoreItem.php
index 8f06660..eb98674 100644
--- a/src/ViewModel/ReadMoreItem.php
+++ b/src/ViewModel/ReadMoreItem.php
@@ -38,12 +38,12 @@ final class ReadMoreItem implements ViewModel
         yield from $this->item->getJavaScripts();
     }
 
-    protected function getComposedViewModels(): Traversable
+    protected function getComposedViewModels() : Traversable
     {
         yield $this->item;
     }
 
-    public function getTemplateName(): string
+    public function getTemplateName() : string
     {
         return 'resources/templates/read-more-item.mustache';
     }
diff --git a/src/ViewModel/Select.php b/src/ViewModel/Select.php
index bb07654..f438c08 100644
--- a/src/ViewModel/Select.php
+++ b/src/ViewModel/Select.php
@@ -40,7 +40,7 @@ final class Select implements ViewModel
         Assertion::notEmpty($options);
         Assertion::allIsInstanceOf($options, SelectOption::class);
         Assertion::nullOrChoice($state, [self::STATE_INVALID, self::STATE_VALID]);
-        if ($state === self::STATE_INVALID) {
+        if (self::STATE_INVALID === $state) {
             Assertion::notNull($messageGroup);
             Assertion::notBlank($messageGroup['errorText']);
         }
diff --git a/src/ViewModel/Statistic.php b/src/ViewModel/Statistic.php
index 5cddc09..dc93c03 100644
--- a/src/ViewModel/Statistic.php
+++ b/src/ViewModel/Statistic.php
@@ -37,12 +37,12 @@ final class Statistic implements ViewModel
         $this->value = $value;
     }
 
-    public function getStyleSheets(): Traversable
+    public function getStyleSheets() : Traversable
     {
         yield 'resources/assets/css/statistic.css';
     }
 
-    public function getTemplateName(): string
+    public function getTemplateName() : string
     {
         return 'resources/templates/statistic.mustache';
     }
diff --git a/src/ViewModel/StatisticCollection.php b/src/ViewModel/StatisticCollection.php
index a61a8c1..fb8eb2d 100644
--- a/src/ViewModel/StatisticCollection.php
+++ b/src/ViewModel/StatisticCollection.php
@@ -24,17 +24,17 @@ final class StatisticCollection implements ViewModel
         $this->stats = $stats;
     }
 
-    protected function getLocalStyleSheets(): Traversable
+    protected function getLocalStyleSheets() : Traversable
     {
         yield 'resources/assets/css/statistic-collection.css';
     }
 
-    protected function getComposedViewModels(): Traversable
+    protected function getComposedViewModels() : Traversable
     {
         yield from $this->stats;
     }
 
-    public function getTemplateName(): string
+    public function getTemplateName() : string
     {
         return 'resources/templates/statistic-collection [...]

2018-03-08 15:49 UTC, giorgiosironi commented
And api-sdk, which is very similar but also found some `final private` issues:
```
diff --git a/src/Model/Address.php b/src/Model/Address.php
index ddb2320..834f908 100644
--- a/src/Model/Address.php
+++ b/src/Model/Address.php
@@ -35,7 +35,7 @@ final class Address
     /**
      * @return Sequence|string[]
      */
-    public function getFormatted(): Sequence
+    public function getFormatted() : Sequence
     {
         return $this->formatted;
     }
@@ -43,7 +43,7 @@ final class Address
     /**
      * @return Sequence|string[]
      */
-    public function getStreetAddress(): Sequence
+    public function getStreetAddress() : Sequence
     {
         return $this->streetAddress;
     }
@@ -51,7 +51,7 @@ final class Address
     /**
      * @return Sequence|string[]
      */
-    public function getLocality(): Sequence
+    public function getLocality() : Sequence
     {
         return $this->locality;
     }
@@ -59,7 +59,7 @@ final class Address
     /**
      * @return Sequence|string[]
      */
-    public function getArea(): Sequence
+    public function getArea() : Sequence
     {
         return $this->area;
     }
diff --git a/src/Model/AnnualReport.php b/src/Model/AnnualReport.php
index 0726e73..d25aa96 100644
--- a/src/Model/AnnualReport.php
+++ b/src/Model/AnnualReport.php
@@ -26,12 +26,12 @@ final class AnnualReport implements Model, HasIdentifier, HasImpactStatement, Ha
         return Identifier::annualReport($this->year);
     }
 
-    public function getYear(): int
+    public function getYear() : int
     {
         return $this->year;
     }
 
-    public function getUri(): string
+    public function getUri() : string
     {
         return $this->uri;
     }
@@ -44,7 +44,7 @@ final class AnnualReport implements Model, HasIdentifier, HasImpactStatement, Ha
         return $this->pdf;
     }
 
-    public function getTitle(): string
+    public function getTitle() : string
     {
         return $this->title;
     }
@@ -57,7 +57,7 @@ final class AnnualReport implements Model, HasIdentifier, HasImpactStatement, Ha
         return $this->impactStatement;
     }
 
-    public function getImage(): Image
+    public function getImage() : Image
     {
         return $this->image;
     }
diff --git a/src/Model/Author.php b/src/Model/Author.php
index 4ca6968..548972b 100644
--- a/src/Model/Author.php
+++ b/src/Model/Author.php
@@ -47,7 +47,7 @@ abstract class Author implements AuthorEntry
     /**
      * @return Place[]
      */
-    final public function getAffiliations(): array
+    final public function getAffiliations() : array
     {
         return $this->affiliations;
     }
@@ -71,7 +71,7 @@ abstract class Author implements AuthorEntry
     /**
      * @return string[]
      */
-    final public function getEmailAddresses(): array
+    final public function getEmailAddresses() : array
     {
         return $this->emailAddresses;
     }
@@ -79,7 +79,7 @@ abstract class Author implements AuthorEntry
     /**
      * @return int[]
      */
-    final public function getEqualContributionGroups(): array
+    final public function getEqualContributionGroups() : array
     {
         return $this->equalContributionGroups;
     }
@@ -87,7 +87,7 @@ abstract class Author implements AuthorEntry
     /**
      * @return string[]
      */
-    final public function getPhoneNumbers(): array
+    final public function getPhoneNumbers() : array
     {
         return $this->phoneNumbers;
     }
@@ -95,7 +95,7 @@ abstract class Author implements AuthorEntry
     /**
      * @return Address[]
      */
-    final public function getPostalAddresses(): array
+    final public function getPostalAddresses() : array
     {
         return $this->postalAddresses;
     }
diff --git a/src/Model/Block/VideoSource.php b/src/Model/Block/VideoSource.php
index 7b30633..d818dcf 100644
--- a/src/Model/Block/VideoSource.php
+++ b/src/Model/Block/VideoSource.php
@@ -16,12 +16,12 @@ final class VideoSource
         $this->uri = $uri;
     }
 
-    public function getMediaType(): string
+    public function getMediaType() : string
     {
         return $this->mediaType;
     }
 
-    public function getUri(): string
+    public function getUri() : string
     {
         return $this->uri;
     }
diff --git a/src/Model/Copyright.php b/src/Model/Copyright.php
index 06ec8f4..80d5b2a 100644
--- a/src/Model/Copyright.php
+++ b/src/Model/Copyright.php
@@ -18,7 +18,7 @@ final class Copyright
     /**
      * @return string
      */
-    public function getLicense(): string
+    public function getLicense() : string
     {
         return $this->license;
     }
@@ -26,7 +26,7 @@ final class Copyright
     /**
      * @return string
      */
-    public function getStatement(): string
+    public function getStatement() : string
     {
         return $this->statement;
     }
diff --git a/src/Model/DataSet.php b/src/Model/DataSet.php
index 9be9003..15efacf 100644
--- a/src/Model/DataSet.php
+++ b/src/Model/DataSet.php
@@ -39,12 +39,12 @@ final class DataSet implements HasDoi, HasId
         $this->uri = $uri;
     }
 
-    public function getId(): string
+    public function getId() : string
     {
         return $this->id;
     }
 
-    public function getDate(): Date
+    public function getDate() : Date
     {
         return $this->date;
     }
@@ -52,17 +52,17 @@ final class DataSet implements HasDoi, HasId
     /**
      * @return AuthorEntry[]
      */
-    public function getAuthors(): array
+    public function getAuthors() : array
     {
         return $this->authors;
     }
 
-    public function authorsEtAl(): bool
+    public function authorsEtAl() : bool
     {
         return $this->authorsEtAl;
     }
 
-    public function getTitle(): string
+    public function getTitle() : string
     {
         return $this->title;
     }
diff --git a/src/Model/ExternalArticle.php b/src/Model/ExternalArticle.php
index e67b1b8..f2cf2ee 100644
--- a/src/Model/ExternalArticle.php
+++ b/src/Model/ExternalArticle.php
@@ -20,32 +20,32 @@ final class ExternalArticle implements Article
         $this->uri = $uri;
     }
 
-    public function getTitle(): string
+    public function getTitle() : string
     {
         return $this->articleTitle;
     }
 
-    public function getAuthorLine(): string
+    public function getAuthorLine() : string
     {
         return $this->authorLine;
     }
 
-    public function getJournal(): string
+    public function getJournal() : string
     {
         return $this->journal;
     }
 
-    public function getUri(): string
+    public function getUri() : string
     {
         return $this->uri;
     }
 
-    public function getId(): string
+    public function getId() : string
     {
         return 'external-'.sha1($this->uri);
     }
 
-    public function getType(): string
+    public function getType() : string
     {
         return 'external-article';
     }
diff --git a/src/Model/Funder.php b/src/Model/Funder.php
index c265567..998778e 100644
--- a/src/Model/Funder.php
+++ b/src/Model/Funder.php
@@ -16,7 +16,7 @@ final class Funder
         $this->funderId = $funderId;
     }
 
-    public function getPlace(): Place
+    public function getPlace() : Place
     {
         return $this->place;
     }
diff --git a/src/Model/Funding.php b/src/Model/Funding.php
index 7a60c22..924b25c 100644
--- a/src/Model/Funding.php
+++ b/src/Model/Funding.php
@@ -21,7 +21,7 @@ final class Funding
     /**
      * @return Sequence|FundingAward[]
      */
-    public function getAwards(): Sequence
+    public function getAwards() : Sequence
     {
         return $this->awards;
     }
diff --git a/src/Model/FundingAward.php b/src/Model/FundingAward.php
index beb587f..6170722 100644
--- a/src/Model/FundingAward.php
+++ b/src/Model/FundingAward.php
@@ -22,12 +22,12 @@ final class FundingAward implements HasId
         $this->recipients = $recipients;
     }
 
-    public function getId(): string
+    public function getId() : string
     {
        [...]

2018-03-09 08:17 UTC, thewilkybarkid commented on .php_cs
> +        //'empty_return' => false,
Looks like `simplified_null_return`.

2018-03-09 11:16 UTC, giorgiosironi commented
Now allows `return null;` to be used instead of changing it to `return;`. This seems to be the default however so we may not need to turn `simplified_null_return` off?

2018-03-12 11:33 UTC, thewilkybarkid approved these changes
There might be more rules we should enable, but looks good for now.

2018-03-13 07:49 UTC, thewilkybarkid requested changes
Need to do some more testing. Tried new version of PHP-CS-Fixer on Journal and it ignored all the exclusions, so ended up fixing the cache directory etc.

2018-03-13 10:05 UTC, thewilkybarkid approved these changes
Seems ok actually, I'd been used `php-cs-fixer fix .` which overrides the finder, but works correctly without specifying the path.

2018-03-13 10:07 UTC, merged